// Перевод имён SF Symbols в Material Symbols.
//
// expo-symbols на Android рисует глиф шрифта Material Symbols и требует android-имя:
// со строковым именем SF-символа (`name="person.crop.circle"`) он покажет пустоту.
// Таблица закрывает все иконки, что встречаются в приложении; остальное разбирает
// эвристика — суффикс `.fill`/`.circle` в Material не отдельная иконка, а вариант.
const TABLE: Record<string, string> = {
  // навигация и действия
  'chevron.left': 'chevron_left',
  'chevron.right': 'chevron_right',
  'chevron.up.chevron.down': 'unfold_more',
  'chevron.up': 'keyboard_arrow_up',
  'chevron.down': 'keyboard_arrow_down',
  xmark: 'close',
  'xmark.circle': 'cancel',
  'xmark.octagon': 'dangerous',
  plus: 'add',
  'plus.circle': 'add_circle',
  'plus.magnifyingglass': 'zoom_in',
  minus: 'remove',
  'minus.circle': 'remove_circle',
  checkmark: 'check',
  'checkmark.circle': 'check_circle',
  'checkmark.seal': 'verified',
  'checkmark.shield': 'verified_user',
  ellipsis: 'more_horiz',
  'ellipsis.circle': 'more_horiz',
  magnifyingglass: 'search',
  pencil: 'edit',
  'pencil.circle': 'edit',
  trash: 'delete',
  'delete.left': 'backspace',
  'square.and.arrow.up': 'ios_share',
  'rectangle.portrait.and.arrow.right': 'logout',
  'arrow.uturn.backward': 'undo',
  'arrow.uturn.backward.circle': 'undo',
  'arrow.left.arrow.right': 'swap_horiz',
  'arrow.up.arrow.down': 'swap_vert',
  'arrow.up.circle': 'arrow_circle_up',
  'arrow.down.circle': 'arrow_circle_down',
  'arrow.down.right.circle': 'arrow_circle_down',
  'arrow.up.right': 'north_east',
  'arrow.up.to.line': 'vertical_align_top',
  'arrow.triangle.2.circlepath': 'sync',
  'arrow.clockwise.icloud': 'cloud_sync',
  'tray.and.arrow.down': 'download',
  nosign: 'block',
  eye: 'visibility',

  // деньги и касса
  banknote: 'payments',
  cash: 'payments',
  creditcard: 'credit_card',
  'creditcard.and.123': 'credit_card',
  rublesign: 'currency_ruble',
  'rublesign.circle': 'currency_ruble',
  wallet: 'wallet',
  'wallet.bifold': 'wallet',
  giftcard: 'redeem',
  gift: 'card_giftcard',
  // значки категорий меню (CATEGORY_SYMBOLS в lib/catalog-api.ts)
  waterbottle: 'local_drink',
  'cup.and.heat.waves': 'coffee',
  popcorn: 'cookie',
  flame: 'local_fire_department',
  wineglass: 'wine_bar',
  mug: 'sports_bar',
  leaf: 'eco',
  'sun.horizon': 'wb_twilight',
  dice: 'casino',
  'fork.knife.circle': 'local_pizza',
  'hand.raised': 'front_hand',
  'figure.2.and.child.holdinghands': 'family_restroom',
  'birthday.cake': 'cake',
  'party.popper': 'celebration',
  percent: 'percent',
  discount: 'percent',
  sum: 'functions',
  receipt: 'receipt',
  qrcode: 'qr_code',
  cart: 'shopping_cart',

  // люди
  person: 'person',
  'person.2': 'group',
  'person.3': 'groups',
  'person.crop.circle': 'account_circle',
  'person.crop.circle.badge.checkmark': 'how_to_reg',
  'person.crop.circle.badge.plus': 'person_add',
  'person.crop.circle.badge.questionmark': 'person_search',
  'person.crop.circle.badge.xmark': 'person_off',
  'person.badge.plus': 'person_add',
  'person.badge.minus': 'person_remove',
  'person.badge.key': 'admin_panel_settings',
  'person.badge.clock': 'manage_accounts',
  'person.badge.shield.checkmark': 'verified_user',
  'person.text.rectangle': 'badge',
  'figure.walk': 'directions_walk',
  'hand.raised.fill': 'front_hand',
  crown: 'workspace_premium',
  trophy: 'trophy',
  'suit.spade': 'casino',
  faceid: 'face',
  touchid: 'fingerprint',

  // заведение и склад
  house: 'home',
  'building.2': 'apartment',
  'building.columns': 'account_balance',
  'door.french.closed': 'door_front',
  'door.left.hand.closed': 'door_front',
  'table.furniture': 'table_restaurant',
  archivebox: 'inventory_2',
  shippingbox: 'inventory_2',
  externaldrive: 'storage',
  'server.rack': 'dns',
  briefcase: 'work',
  menucard: 'menu_book',
  'fork.knife': 'restaurant',
  food: 'restaurant',
  'cup.and.saucer': 'local_cafe',
  'takeoutbag.and.cup.and.straw': 'takeout_dining',
  'drop.fill': 'water_drop',
  'smoke.fill': 'smoking_rooms',
  gamecontroller: 'sports_esports',
  ticket: 'confirmation_number',

  // связь и уведомления
  bell: 'notifications',
  'bell.badge': 'notifications_active',
  'bubble.left': 'chat_bubble',
  'bubble.left.and.bubble.right': 'forum',
  'text.bubble': 'comment',
  'message.fill': 'chat',
  chat: 'chat',
  'envelope.badge': 'mark_email_unread',
  paperplane: 'send',
  megaphone: 'campaign',
  'square.and.pencil': 'edit_square',
  iphone: 'smartphone',
  circle: 'radio_button_unchecked',
  phone: 'phone',
  'wifi.slash': 'wifi_off',
  'wifi.exclamationmark': 'signal_wifi_bad',

  // время и календарь
  clock: 'schedule',
  'clock.arrow.circlepath': 'history',
  'clock.badge.checkmark': 'alarm_on',
  timer: 'timer',
  hourglass: 'hourglass',
  calendar: 'calendar_month',
  'calendar.badge.plus': 'calendar_add_on',
  'calendar.badge.checkmark': 'event_available',
  'calendar.badge.clock': 'event_upcoming',
  events: 'event',
  sunrise: 'wb_twilight',
  'sun.max': 'light_mode',
  moon: 'dark_mode',
  'moon.stars': 'bedtime',
  'moon.zzz': 'bedtime',

  // документы, аналитика, система
  'doc.text': 'description',
  checklist: 'checklist',
  checks: 'checklist',
  'list.bullet': 'format_list_bulleted',
  'text.alignleft': 'format_align_left',
  'textformat.abc': 'abc',
  'chart.bar': 'bar_chart',
  'chart.xyaxis.line': 'show_chart',
  analytics: 'analytics',
  index: 'list',
  'square.grid.2x2': 'grid_view',
  'square.split.2x1': 'splitscreen',
  'square.split.bottomrightquarter': 'splitscreen',
  'slider.horizontal.3': 'tune',
  'gearshape.2': 'settings',
  'wrench.and.screwdriver': 'build',
  'info.circle': 'info',
  'questionmark.circle': 'help',
  'exclamationmark.circle': 'error',
  'exclamationmark.triangle': 'warning',
  'lock.fill': 'lock',
  lock: 'lock',
  key: 'key',
  signature: 'signature',
  sparkles: 'auto_awesome',
  'bolt.fill': 'bolt',
  'flame.fill': 'local_fire_department',
  heart: 'favorite',
  star: 'star',
  'star.circle': 'stars',
  flag: 'flag',
  tag: 'label',
  'tag.slash': 'label_off',
  number: 'numbers',
  'number.circle': 'numbers',
  folder: 'folder',
  'folder.badge.plus': 'create_new_folder',
  link: 'link',
  'link.badge.plus': 'add_link',
  map: 'map',
  'mappin.and.ellipse': 'place',
  mappin: 'location_on',
  'location.fill': 'location_on',
  car: 'directions_car',
  camera: 'photo_camera',
  'play.fill': 'play_arrow',
  'play.circle': 'play_circle',
  'ipad.landscape': 'tablet',
  visionpro: 'view_in_ar',
  other: 'more_horiz',
  close: 'close',
  edit: 'edit',
};

/**
 * Имя Material Symbols для SF-символа, либо null — тогда место иконки остаётся пустым,
 * и вёрстка не прыгает.
 */
export function toMaterialSymbol(sf: string, exists?: (name: string) => boolean): string | null {
  if (!sf) return null;
  const candidates: string[] = [];
  const push = (value: string | undefined) => { if (value && !candidates.includes(value)) candidates.push(value); };

  push(TABLE[sf]);
  // `.fill` в Material — не отдельная иконка, а начертание того же символа.
  const base = sf.replace(/\.fill$/, '');
  push(TABLE[base]);
  push(TABLE[base.replace(/\.circle$/, '')]);
  push(base.replace(/\./g, '_'));
  push(base.split('.')[0]);

  if (!exists) return candidates[0] ?? null;
  return candidates.find(exists) ?? null;
}
