plugins {
  id 'com.android.library'
  id 'expo-module-gradle-plugin'
}

group = 'ru.titan.home'
version = '1.0.0'

android {
  namespace "expo.modules.titanha"
  defaultConfig {
    versionCode 1
    versionName "1.0.0"
  }
}

dependencies {
  // Та же версия, что у React Native (react-native/gradle/libs.versions.toml).
  implementation "com.squareup.okhttp3:okhttp:4.9.2"
}
